#!/bin/bash

[ "$#" -lt 2 ] && exit 1
destdir=$1
release=$2

dnf -y install \
    --installroot=${destdir} \
    --releasever=${release} \
    --disablerepo=\* --enablerepo=fedora,updates \
    audit bash binutils bzip2 coreutils cpio curl debugedit \
    diffutils elfutils-libelf elfutils-libs file file-libs \
    findutils gawk gcc gdb-headless gdb-minimal glibc gpg grep gzip \
    ima-evm-utils libacl libarchive libcap libfsverity libgcc \
    libgomp libzstd lua-libs make openssl-libs patch \
    pkgconf-pkg-config python3 rpm-sequoia sed sqlite-libs tar \
    unzip xz xz-libs zlib zstd

[ "${destdir}" == "/" ] || rm -rf ${destdir}/usr/lib/sysimage/*
