#!/bin/sh

MAKE=$1
TOPDIR=$2
BINDIR=$3
SRCDIR=$4

btrfs subvolume create testing

dnf -y install --disablerepo=\* --enablerepo=fedora,updates \
               --releasever=37 --installroot=$BINDIR/testing \
    audit \
    bash \
    binutils \
    bzip2 \
    coreutils \
    cpio \
    curl \
    debugedit \
    diffutils \
    elfutils-libelf \
    elfutils-libs \
    file \
    file-libs \
    findutils \
    gawk \
    gcc \
    gdb-headless \
    gdb-minimal \
    glibc \
    gpg \
    grep \
    gzip \
    ima-evm-utils \
    libacl \
    libarchive \
    libcap \
    libfsverity \
    libgcc \
    libgomp \
    libzstd \
    lua-libs \
    make \
    openssl-libs \
    patch \
    pkgconf-pkg-config \
    python3 \
    rpm-sequoia \
    sed \
    sqlite-libs \
    tar \
    unzip \
    xz \
    xz-libs \
    zlib \
    zstd

cd ${TOPDIR}

${MAKE} DESTDIR=${BINDIR}/testing install
sed -i 's,^%_dbpath\t.*$,%_dbpath /usr/lib/sysimage/rpm,' \
    ${BINDIR}/testing/usr/local/lib/rpm/macros

cp -r ${SRCDIR}/data/ ${BINDIR}/testing/

echo "/usr/local/lib64" > ${BINDIR}/testing/etc/ld.so.conf.d/rpm.conf
ldconfig -r ${BINDIR}/testing
