#!/bin/bash

OS_BASE=$0.@OS_NAME@
IMAGE=rpm

function install()
{
    export DESTDIR=$1

    local profile_dir=$DESTDIR/@CMAKE_INSTALL_SYSCONFDIR@/profile.d
    local ld_conf_dir=$DESTDIR/@CMAKE_INSTALL_SYSCONFDIR@/ld.so.conf.d

    @CMAKE_MAKE_PROGRAM@ -C @CMAKE_BINARY_DIR@ install
    mkdir -p $profile_dir $ld_conf_dir
    echo "export PATH=@CMAKE_INSTALL_FULL_BINDIR@:/usr/bin" > \
        $profile_dir/rpm.sh
    echo @CMAKE_INSTALL_FULL_LIBDIR@ > \
        $ld_conf_dir/rpm.conf
    ldconfig -r $DESTDIR @CMAKE_INSTALL_FULL_LIBDIR@

    cp -r @CMAKE_CURRENT_SOURCE_DIR@/data $DESTDIR/

    mkdir -p $DESTDIR/usr/bin
    cp @TESTPROGS_STR@ $DESTDIR/usr/bin/

    mkdir -p $DESTDIR/build
    ln -sf /data/SOURCES $DESTDIR/build/
}

function bwo()
{
    local cmd=$1
    shift
    case $cmd in
        build)
            [ -d mktree.output/base ] && return
            $OS_BASE build
        ;;
        install)
            rm -rf mktree.output/inst
            install $PWD/mktree.output/inst
        ;;
        shell)
            set -a
            source ./atlocal
            RPMTREE=$PWD/mktree.output/inst:$PWD/mktree.output/base
            RPMTEST=$PWD/mktree.sandbox/merged
            rm -rf mktree.sandbox
            sandbox mount mktree.sandbox
            sandbox shell "$@"
            sandbox umount $RPMTEST
        ;;
        env)
            set -a
            source ./atlocal
            RPMTREE=$PWD/mktree.output/inst:$PWD/mktree.output/base
            RPMTEST=$PWD/mktree.sandbox/merged
            rm -rf mktree.sandbox
            sandbox mount mktree.sandbox
            $SHELL
            sandbox umount $RPMTEST
        ;;
    esac
}

function oci()
{
    local cmd=$1
    shift
    case $cmd in
        build)
            podman image exists $IMAGE ||
            podman build -t $IMAGE \
                -f @CMAKE_SOURCE_DIR@/ci/Dockerfile \
                @CMAKE_SOURCE_DIR@
        ;;
        install)
            name=$(buildah from $IMAGE)
            dir=$(buildah mount $name)

            if [ "$1" == "--reuse" ]; then
                cp -pr $2/* $dir/
            else
                install $dir
            fi

            buildah images -q $IMAGE-new >/dev/null 2>&1 && buildah rmi $IMAGE-new
            buildah commit $name $IMAGE-new
            buildah umount $name
            buildah rm $name
        ;;
        shell)
            podman run --privileged --read-only -it --rm -v $PWD:/srv --workdir /srv $IMAGE-new "$@"
        ;;
        env)
            set -a
            source ./atlocal
            name=$(buildah from $IMAGE-new)
            dir=$(buildah mount $name)
            RPMTREE=/
            RPMTEST=$dir
            $SHELL
            buildah umount $name
            buildah rm $name
        ;;
    esac
}

$1 "${@:2}"
