#!/bin/sh

top_builddir="$1"
abs_builddir="$2"
srcdir="$3"
bindir="$4"
MAKE="$5"

btrfs subvolume delete testing
btrfs subvolume create testing
cp -r ../../rpm/image/* testing/

sed -i 's,^%_dbpath\t.*$,%_dbpath /usr/lib/sysimage/rpm,' ${abs_builddir}/testing/usr/lib/rpm/macros

cp -r ${srcdir}/data/ testing/
for d in magic; do
	if [ ! -d testing/${d} ]; then
		mkdir testing/${d}
	fi
done
(cd testing/magic && cp /usr/share/misc/magic.mgc . || file -C)
