#!/bin/bash

function snapshot()
{
    local cmd=$1
    shift
    case $cmd in
        mount)
            mkdir -p $1/diff $1/work ${RPMTEST}
            mount -t overlay $(basename $1) \
                  -o userxattr \
                  -o lowerdir="${RPMTREE}" \
                  -o upperdir=$1/diff \
                  -o workdir=$1/work \
                  ${RPMTEST}
        ;;
        umount)
            umount -ql $RPMTEST
        ;;
        prune)
            local dir
            for dir in "$@"; do
                [ -d "$dir" ] && umount -ql $dir
            done
            return 0
        ;;
        exec)
            bwrap --unshare-pid --dev-bind $RPMTEST / --clearenv \
                  --setenv PATH $PATH --setenv HOME /root \
                  --dev /dev --proc /proc --die-with-parent "$@"
        ;;
        shell)
            local source=$(findmnt -no SOURCE --mountpoint $RPMTEST)
            local passwd=$RPMTEST/etc/passwd
            if [ $# == 0 ]; then
                if [ -f "$passwd" ]; then
                    set -- $(grep ^root: $passwd | cut -d: -f7)
                else
                    set -- sh
                fi
            fi
            snapshot exec --unshare-uts --hostname $source \
                          --setenv TERM $TERM "$@"
        ;;
    esac
}
