#!/bin/sh
set -e

PODMAN=$1
BINDIR=$2

mkdir -p $BINDIR
cd $(dirname $0)/..

$PODMAN build -t rpm -f ci/Dockerfile .
$PODMAN run --privileged -it --rm \
    -v $PWD:/srv/src:ro \
    -v $BINDIR:/srv/bin \
    --workdir /srv/bin rpm \
    sh -c 'cmake \
            -DENABLE_WERROR=ON \
            -DENABLE_BDB_RO=ON \
            -DWITH_FSVERITY=ON \
            -DWITH_IMAEVM=ON \
            /srv/src && \
            make -j$(nproc) check; rc=$?; \
            find . -name rpmtests.log|xargs cat; \
            exit $rc'
