name: Linux CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Fedora testing environment
        run: ./mktree.oci build
        working-directory: ./tests
      - name: Run the test suite
        run: ./mktree.oci check --interactive=false -j$(nproc)
        working-directory: ./tests

    env:
      MKTREE_ENGINE: docker
