name: Linux CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Fedora testing environment
        run: docker build -t rpm -f ci/Dockerfile .
      - name: Run the test suite
        run: docker run -t rpm
